base: Set WEBOS_COMPOSITOR_DISPLAY_CONFIG from configd if available
Change-Id: Id0813c6a2ed4d4218f2be36731ee0728a6058288

diff --git a/base/startup/product.env.in b/base/startup/product.env.in
--- a/base/startup/product.env.in
+++ b/base/startup/product.env.in
@@ -39,106 +39,112 @@ export QT_SCALE_FACTOR=1.0
 # Needed since Qt 5.11
 export QT_QPA_EGLFS_ALWAYS_SET_MODE=1
 
-# Display device detection
-# DRM_CONNECTORS_EXPECTED of 0 doesn't specify the number of DRM connectors
-# which means that it starts with all DRM connectors detected at this point.
-# DRM_PROBE_RETRY is valid only if DRM_CONNECTORS_EXPECTED > 0.
-# DRM_CONNECTORS_SCAN_PRIORITY is the list of connector names interested in order.
-# Use "*" to scan any connectors in alphabetical order.
-WEBOS_COMPOSITOR_DISPLAYS=0
-WEBOS_COMPOSITOR_PRIMARY_SCREEN=""
-DRM_PROBE_RETRY=10
-DRM_CONNECTORS_EXPECTED=0
-DRM_CONNECTORS_SCAN_PRIORITY="*"
-DRM_CONNECTORS_DETECTED_LIST="$XDG_RUNTIME_DIR/surface-manager.display.lst"
-pmlog info "Probing display devices ..."
+# Try to get WEBOS_COMPOSITOR_DISPLAY_CONFIG from configd
+WEBOS_COMPOSITOR_DISPLAY_CONFIG=$(luna-send -n 1 -a com.webos.surfacemanager luna://com.webos.service.config/getConfigs '{"configNames":["com.webos.surfacemanager.displayConfig"]}' | grep -oE "\[\{.*\}\]" || echo "x")
 
-check_drm_connector() {
-    bn=$(basename $1)
-    device=${bn%%-*};    bn=${bn#$device-}
-    connector=${bn%%-*}; bn=${bn#$connector-}
-    sb=${bn%%-*};        bn=${bn#$sb-}
-    id=${bn%%-*}
-    enabled=$(cat "$1/enabled")
-    status=$(cat "$1/status")
-    # Assume available if it reports something other than disconnected
-    # because some DRM connector doesn't report its status correctly.
-    if [ "$status" == "connected" ]; then
-        pmlog info "Display device to use: $device, $connector$id"
-        echo "/dev/dri/$device $connector$id $WEBOS_COMPOSITOR_GEOMETRY" >> $DRM_CONNECTORS_DETECTED_LIST
-        WEBOS_COMPOSITOR_DISPLAYS=$(expr $WEBOS_COMPOSITOR_DISPLAYS + 1)
-        if [ -z "$WEBOS_COMPOSITOR_PRIMARY_SCREEN" ]; then
-            WEBOS_COMPOSITOR_PRIMARY_SCREEN="$connector$id"
-        fi
-    else
-        pmlog warning "Display device unusable: $device, $connector$id ($enabled, $status)"
-    fi
-}
-
-while true; do
+if [ "$WEBOS_COMPOSITOR_DISPLAY_CONFIG" == "x" ]; then
+    # Display device detection
+    # DRM_CONNECTORS_EXPECTED of 0 doesn't specify the number of DRM connectors
+    # which means that it starts with all DRM connectors detected at this point.
+    # DRM_PROBE_RETRY is valid only if DRM_CONNECTORS_EXPECTED > 0.
+    # DRM_CONNECTORS_SCAN_PRIORITY is the list of connector names interested in order.
+    # Use "*" to scan any connectors in alphabetical order.
     WEBOS_COMPOSITOR_DISPLAYS=0
-    cat /dev/null > $DRM_CONNECTORS_DETECTED_LIST
-    set -f; for k in $DRM_CONNECTORS_SCAN_PRIORITY; do
-        pmlog info "Connector to scan: $k"
-        set +f
-        for f in $(find /sys/class/drm -name "card*-$k-*" | sort); do
-            check_drm_connector $f
-            if [ $DRM_CONNECTORS_EXPECTED -gt 0 -a $WEBOS_COMPOSITOR_DISPLAYS -ge $DRM_CONNECTORS_EXPECTED ]; then
+    WEBOS_COMPOSITOR_PRIMARY_SCREEN=""
+    DRM_PROBE_RETRY=10
+    DRM_CONNECTORS_EXPECTED=0
+    DRM_CONNECTORS_SCAN_PRIORITY="*"
+    DRM_CONNECTORS_DETECTED_LIST="$XDG_RUNTIME_DIR/surface-manager.display.lst"
+    pmlog info "Generating WEBOS_COMPOSITOR_DISPLAY_CONFIG based on /sys/class/drm ..."
+
+    check_drm_connector() {
+        bn=$(basename $1)
+        device=${bn%%-*};    bn=${bn#$device-}
+        connector=${bn%%-*}; bn=${bn#$connector-}
+        sb=${bn%%-*};        bn=${bn#$sb-}
+        id=${bn%%-*}
+        enabled=$(cat "$1/enabled")
+        status=$(cat "$1/status")
+        # Assume available if it reports something other than disconnected
+        # because some DRM connector doesn't report its status correctly.
+        if [ "$status" == "connected" ]; then
+            pmlog info "Display device to use: $device, $connector$id"
+            echo "/dev/dri/$device $connector$id $WEBOS_COMPOSITOR_GEOMETRY" >> $DRM_CONNECTORS_DETECTED_LIST
+            WEBOS_COMPOSITOR_DISPLAYS=$(expr $WEBOS_COMPOSITOR_DISPLAYS + 1)
+            if [ -z "$WEBOS_COMPOSITOR_PRIMARY_SCREEN" ]; then
+                WEBOS_COMPOSITOR_PRIMARY_SCREEN="$connector$id"
+            fi
+        else
+            pmlog warning "Display device unusable: $device, $connector$id ($enabled, $status)"
+        fi
+    }
+
+    while true; do
+        WEBOS_COMPOSITOR_DISPLAYS=0
+        cat /dev/null > $DRM_CONNECTORS_DETECTED_LIST
+        set -f; for k in $DRM_CONNECTORS_SCAN_PRIORITY; do
+            pmlog info "Connector to scan: $k"
+            set +f
+            for f in $(find /sys/class/drm -name "card*-$k-*" | sort); do
+                check_drm_connector $f
+                if [ $DRM_CONNECTORS_EXPECTED -gt 0 -a $WEBOS_COMPOSITOR_DISPLAYS -ge $DRM_CONNECTORS_EXPECTED ]; then
+                    break
+                fi
+            done
+        done
+
+        if [ $DRM_CONNECTORS_EXPECTED -eq 0 -a $WEBOS_COMPOSITOR_DISPLAYS -gt 0 ]; then
+            pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected."
+            break
+        elif [ $DRM_CONNECTORS_EXPECTED -gt 0 -a $WEBOS_COMPOSITOR_DISPLAYS -ge $DRM_CONNECTORS_EXPECTED ]; then
+            pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected as expected."
+            break
+        else
+            # Detection incomplete.
+            # TODO: Consider using inotify rather than polling.
+            if [ $WEBOS_COMPOSITOR_DISPLAYS -eq 0 ]; then
+                pmlog crit "No display device detected"
+                # Retry until at least one connector becomes available
+                sleep 10
+            elif [ $DRM_PROBE_RETRY -gt 0 ]; then
+                pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected, expecting $DRM_CONNECTORS_EXPECTED"
+                DRM_PROBE_RETRY=$(expr $DRM_PROBE_RETRY - 1)
+                sleep 1
+            else
+                pmlog warning "Failed to detect $DRM_CONNECTORS_EXPECTED display device(s). Detected $WEBOS_COMPOSITOR_DISPLAYS only."
                 break
             fi
-        done
+        fi
     done
 
-    if [ $DRM_CONNECTORS_EXPECTED -eq 0 -a $WEBOS_COMPOSITOR_DISPLAYS -gt 0 ]; then
-        pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected."
-        break
-    elif [ $DRM_CONNECTORS_EXPECTED -gt 0 -a $WEBOS_COMPOSITOR_DISPLAYS -ge $DRM_CONNECTORS_EXPECTED ]; then
-        pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected as expected."
-        break
-    else
-        # Detection incomplete.
-        # TODO: Consider using inotify rather than polling.
-        if [ $WEBOS_COMPOSITOR_DISPLAYS -eq 0 ]; then
-            pmlog crit "No display device detected"
-            # Retry until at least one connector becomes available
-            sleep 10
-        elif [ $DRM_PROBE_RETRY -gt 0 ]; then
-            pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected, expecting $DRM_CONNECTORS_EXPECTED"
-            DRM_PROBE_RETRY=$(expr $DRM_PROBE_RETRY - 1)
-            sleep 1
-        else
-            pmlog warning "Failed to detect $DRM_CONNECTORS_EXPECTED display device(s). Detected $WEBOS_COMPOSITOR_DISPLAYS only."
-            break
-        fi
-    fi
-done
+    WEBOS_COMPOSITOR_DISPLAY_CONFIG=$(awk '
+        BEGIN {
+            dri = ""
+            printf "["
+        }
+        /^\/dev\/dri\// {
+            if ( dri != $1 ) {
+                if ( dri != "" )
+                    printf "]}"
+                printf "{\"device\":\"%s\",\"hwcursor\":false,\"outputs\":[", $1
+                dri = $1
+            } else {
+                printf ","
+            }
+            printf "{\"name\":\"%s\",\"geometry\":\"%s\"}", $2, $3
+        }
+        END {
+            if ( dri != "" )
+                printf "]}"
+            printf "]"
+        }
+        ' $DRM_CONNECTORS_DETECTED_LIST)
+fi
 
 # Generate EGLFS config json file based on devices detected.
 # Assume the order of touchscreen devices are the same with
 # the order of DRM connectors.
 QT_QPA_EGLFS_CONFIG="$XDG_RUNTIME_DIR/surface-manager.eglfs.json"
-WEBOS_COMPOSITOR_DISPLAY_CONFIG=$(awk '
-    BEGIN {
-        dri = ""
-        printf "["
-    }
-    /^\/dev\/dri\// {
-        if ( dri != $1 ) {
-            if ( dri != "" )
-                printf "]}"
-            printf "{\"device\":\"%s\",\"hwcursor\":false,\"outputs\":[", $1
-            dri = $1
-        } else {
-            printf ","
-        }
-        printf "{\"name\":\"%s\",\"geometry\":\"%s\"}", $2, $3
-    }
-    END {
-        if ( dri != "" )
-            printf "]}"
-        printf "]"
-    }
-    ' $DRM_CONNECTORS_DETECTED_LIST)
 
 pmlog info "QT_QPA_EGLFS_CONFIG: $QT_QPA_EGLFS_CONFIG"
 pmlog info "WEBOS_COMPOSITOR_DISPLAYS: $WEBOS_COMPOSITOR_DISPLAYS"
